[package]
name = "pitch-detection"
version = "0.1.0"
authors = ["Alessandro Genova <ales.genova@gmail.com>"]
edition = "2018"

[dependencies]
rustfft = { version = "3.0.0", default-features = false }
num-traits = { version = "0.2", default-features = false }
num-complex = { version = "0.2", default-features = false }
